### ISSUE TITLE
Request to process fast.ai Intro to Machine Learning videos

### ISSUE THREAD

**Issue by cedrickchee** [mingrui/youtube_caption_search#1]
Hi. Thank you for creating this great tool to make it easier to watch fast.ai video lessons.

You mentioned in the README that you are open to taking requests to process other videos.

May I suggest to you that you also process the other fast.ai video lessons as well? I think you can prioritize based on the following:

1. Intro to Machine Learning videos
http://forums.fast.ai/t/another-treat-early-access-to-intro-to-machine-learning-videos/6826?u=cedric
2. Cutting Edge Deep Learning For Coders, Part 2 (version 1 / 2017 version)
http://course.fast.ai/part2.html

Thank you.

**Comment by mingrui** [comment]
Uploaded!
